import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const players = [
  // ===== ENGLAND =====
  { name: "Jordan Pickford", position: "GK", country: "England", clubTeam: "Everton", value: 4.5, sofifaId: "211117" },
  { name: "Aaron Ramsdale", position: "GK", country: "England", clubTeam: "Southampton", value: 3.5, sofifaId: "236524" },
  { name: "Trent Alexander-Arnold", position: "DEF", country: "England", clubTeam: "Real Madrid", value: 6.5, sofifaId: "232592" },
  { name: "Kieran Trippier", position: "DEF", country: "England", clubTeam: "Newcastle", value: 5.5, sofifaId: "210377" },
  { name: "John Stones", position: "DEF", country: "England", clubTeam: "Man City", value: 5, sofifaId: "205447" },
  { name: "Marc Guehi", position: "DEF", country: "England", clubTeam: "Crystal Palace", value: 4.5, sofifaId: "244723" },
  { name: "Luke Shaw", position: "DEF", country: "England", clubTeam: "Man United", value: 4, sofifaId: "209966" },
  { name: "Bukayo Saka", position: "MID", country: "England", clubTeam: "Arsenal", value: 8, sofifaId: "246669" },
  { name: "Jude Bellingham", position: "MID", country: "England", clubTeam: "Real Madrid", value: 10, sofifaId: "237692" },
  { name: "Declan Rice", position: "MID", country: "England", clubTeam: "Arsenal", value: 6.5, sofifaId: "246470" },
  { name: "Eberechi Eze", position: "MID", country: "England", clubTeam: "Arsenal", value: 7.5, sofifaId: "246574" },
  { name: "Cole Palmer", position: "MID", country: "England", clubTeam: "Chelsea", value: 7, sofifaId: "261130" },
  { name: "Harry Kane", position: "FWD", country: "England", clubTeam: "Bayern Munich", value: 9, sofifaId: "202126" },
  { name: "Ollie Watkins", position: "FWD", country: "England", clubTeam: "Aston Villa", value: 6, sofifaId: "221566" },
  { name: "Ivan Toney", position: "FWD", country: "England", clubTeam: "Al-Ahli", value: 4.5, sofifaId: "223349" },

  // ===== FRANCE =====
  { name: "Mike Maignan", position: "GK", country: "France", clubTeam: "AC Milan", value: 5.5, sofifaId: "225029" },
  { name: "Alphonse Areola", position: "GK", country: "France", clubTeam: "West Ham", value: 3.5, sofifaId: "214866" },
  { name: "Jules Koundé", position: "DEF", country: "France", clubTeam: "Barcelona", value: 6, sofifaId: "245692" },
  { name: "Dayot Upamecano", position: "DEF", country: "France", clubTeam: "Bayern Munich", value: 5.5, sofifaId: "243992" },
  { name: "Theo Hernandez", position: "DEF", country: "France", clubTeam: "AC Milan", value: 5.5, sofifaId: "235243" },
  { name: "Benjamin Pavard", position: "DEF", country: "France", clubTeam: "Inter Milan", value: 5, sofifaId: "223750" },
  { name: "Eduardo Camavinga", position: "MID", country: "France", clubTeam: "Real Madrid", value: 6, sofifaId: "262749" },
  { name: "Aurélien Tchouaméni", position: "MID", country: "France", clubTeam: "Real Madrid", value: 6.5, sofifaId: "251611" },
  { name: "Antoine Griezmann", position: "MID", country: "France", clubTeam: "Atletico Madrid", value: 6.5, sofifaId: "194765" },
  { name: "Ousmane Dembélé", position: "MID", country: "France", clubTeam: "PSG", value: 7, sofifaId: "231443" },
  { name: "Kylian Mbappé", position: "FWD", country: "France", clubTeam: "Real Madrid", value: 11, sofifaId: "231747" },
  { name: "Marcus Thuram", position: "FWD", country: "France", clubTeam: "Inter Milan", value: 6.5, sofifaId: "244030" },
  { name: "Olivier Giroud", position: "FWD", country: "France", clubTeam: "LA Galaxy", value: 4, sofifaId: "181985" },

  // ===== BRAZIL =====
  { name: "Alisson Becker", position: "GK", country: "Brazil", clubTeam: "Liverpool", value: 5.5, sofifaId: "212831" },
  { name: "Éderson", position: "GK", country: "Brazil", clubTeam: "Man City", value: 5, sofifaId: "222665" },
  { name: "Éder Militão", position: "DEF", country: "Brazil", clubTeam: "Real Madrid", value: 6.5, sofifaId: "255088" },
  { name: "Marquinhos", position: "DEF", country: "Brazil", clubTeam: "PSG", value: 5.5, sofifaId: "212651" },
  { name: "Danilo", position: "DEF", country: "Brazil", clubTeam: "Flamengo", value: 4, sofifaId: "215451" },
  { name: "Wendell", position: "DEF", country: "Brazil", clubTeam: "Porto", value: 4, sofifaId: "207512" },
  { name: "Bruno Guimarães", position: "MID", country: "Brazil", clubTeam: "Newcastle", value: 6.5, sofifaId: "253088" },
  { name: "Lucas Paquetá", position: "MID", country: "Brazil", clubTeam: "West Ham", value: 6.5, sofifaId: "248980" },
  { name: "Raphinha", position: "MID", country: "Brazil", clubTeam: "Barcelona", value: 7.5, sofifaId: "246923" },
  { name: "Rodrygo", position: "FWD", country: "Brazil", clubTeam: "Real Madrid", value: 7.5, sofifaId: "265524" },
  { name: "Vinicius Jr", position: "FWD", country: "Brazil", clubTeam: "Real Madrid", value: 11, sofifaId: "238794" },
  { name: "Gabriel Martinelli", position: "FWD", country: "Brazil", clubTeam: "Arsenal", value: 6.5, sofifaId: "264607" },
  { name: "Endrick", position: "FWD", country: "Brazil", clubTeam: "Real Madrid", value: 6, sofifaId: "272007" },

  // ===== ARGENTINA =====
  { name: "Emiliano Martínez", position: "GK", country: "Argentina", clubTeam: "Aston Villa", value: 5.5, sofifaId: "198012" },
  { name: "Geronimo Rulli", position: "GK", country: "Argentina", clubTeam: "Ajax", value: 3.5, sofifaId: "213212" },
  { name: "Cristian Romero", position: "DEF", country: "Argentina", clubTeam: "Tottenham", value: 6, sofifaId: "239318" },
  { name: "Nicolás Otamendi", position: "DEF", country: "Argentina", clubTeam: "Benfica", value: 4, sofifaId: "188081" },
  { name: "Nahuel Molina", position: "DEF", country: "Argentina", clubTeam: "Atletico Madrid", value: 5.5, sofifaId: "252009" },
  { name: "Lisandro Martínez", position: "DEF", country: "Argentina", clubTeam: "Man United", value: 5.5, sofifaId: "247003" },
  { name: "Rodrigo De Paul", position: "MID", country: "Argentina", clubTeam: "Atletico Madrid", value: 6, sofifaId: "220502" },
  { name: "Alexis Mac Allister", position: "MID", country: "Argentina", clubTeam: "Liverpool", value: 6.5, sofifaId: "242473" },
  { name: "Enzo Fernández", position: "MID", country: "Argentina", clubTeam: "Chelsea", value: 6.5, sofifaId: "261774" },
  { name: "Ángel Di María", position: "MID", country: "Argentina", clubTeam: "Benfica", value: 5, sofifaId: "183853" },
  { name: "Lionel Messi", position: "FWD", country: "Argentina", clubTeam: "Inter Miami", value: 10, sofifaId: "158023" },
  { name: "Lautaro Martínez", position: "FWD", country: "Argentina", clubTeam: "Inter Milan", value: 7.5, sofifaId: "245351" },
  { name: "Julián Álvarez", position: "FWD", country: "Argentina", clubTeam: "Atletico Madrid", value: 7, sofifaId: "261381" },

  // ===== SPAIN =====
  { name: "Unai Simón", position: "GK", country: "Spain", clubTeam: "Athletic Bilbao", value: 5, sofifaId: "241245" },
  { name: "David Raya", position: "GK", country: "Spain", clubTeam: "Arsenal", value: 5, sofifaId: "213345" },
  { name: "Dani Carvajal", position: "DEF", country: "Spain", clubTeam: "Real Madrid", value: 5.5, sofifaId: "196082" },
  { name: "Aymeric Laporte", position: "DEF", country: "Spain", clubTeam: "Al-Nassr", value: 4.5, sofifaId: "226322" },
  { name: "Robin Le Normand", position: "DEF", country: "Spain", clubTeam: "Atletico Madrid", value: 5, sofifaId: "247131" },
  { name: "Marc Cucurella", position: "DEF", country: "Spain", clubTeam: "Chelsea", value: 4.5, sofifaId: "253658" },
  { name: "Pedri", position: "MID", country: "Spain", clubTeam: "Barcelona", value: 8, sofifaId: "251170" },
  { name: "Rodri", position: "MID", country: "Spain", clubTeam: "Man City", value: 7.5, sofifaId: "222665" },
  { name: "Gavi", position: "MID", country: "Spain", clubTeam: "Barcelona", value: 7.5, sofifaId: "262779" },
  { name: "Dani Olmo", position: "MID", country: "Spain", clubTeam: "Barcelona", value: 6.5, sofifaId: "238813" },
  { name: "Lamine Yamal", position: "MID", country: "Spain", clubTeam: "Barcelona", value: 9, sofifaId: "261289" },
  { name: "Álvaro Morata", position: "FWD", country: "Spain", clubTeam: "AC Milan", value: 5.5, sofifaId: "200389" },
  { name: "Ferran Torres", position: "FWD", country: "Spain", clubTeam: "Barcelona", value: 5.5, sofifaId: "257244" },

  // ===== GERMANY =====
  { name: "Manuel Neuer", position: "GK", country: "Germany", clubTeam: "Bayern Munich", value: 4.5, sofifaId: "167495" },
  { name: "Marc-André ter Stegen", position: "GK", country: "Germany", clubTeam: "Barcelona", value: 4.5, sofifaId: "189049" },
  { name: "Antonio Rüdiger", position: "DEF", country: "Germany", clubTeam: "Real Madrid", value: 6, sofifaId: "208962" },
  { name: "Niklas Süle", position: "DEF", country: "Germany", clubTeam: "Dortmund", value: 4.5, sofifaId: "215941" },
  { name: "Joshua Kimmich", position: "MID", country: "Germany", clubTeam: "Bayern Munich", value: 7.5, sofifaId: "212622" },
  { name: "Thomas Müller", position: "MID", country: "Germany", clubTeam: "Bayern Munich", value: 5.5, sofifaId: "189596" },
  { name: "Florian Wirtz", position: "MID", country: "Germany", clubTeam: "Bayern Munich", value: 9, sofifaId: "264683" },
  { name: "Jamal Musiala", position: "MID", country: "Germany", clubTeam: "Bayern Munich", value: 8.5, sofifaId: "253710" },
  { name: "Leroy Sané", position: "MID", country: "Germany", clubTeam: "Bayern Munich", value: 6.5, sofifaId: "226914" },
  { name: "Kai Havertz", position: "FWD", country: "Germany", clubTeam: "Arsenal", value: 6.5, sofifaId: "223585" },
  { name: "Niclas Füllkrug", position: "FWD", country: "Germany", clubTeam: "West Ham", value: 5.5, sofifaId: "207158" },
  { name: "Deniz Undav", position: "FWD", country: "Germany", clubTeam: "Stuttgart", value: 5, sofifaId: "234729" },

  // ===== PORTUGAL =====
  { name: "Diogo Costa", position: "GK", country: "Portugal", clubTeam: "Porto", value: 5, sofifaId: "253213" },
  { name: "José Sá", position: "GK", country: "Portugal", clubTeam: "Wolves", value: 4, sofifaId: "224617" },
  { name: "João Cancelo", position: "DEF", country: "Portugal", clubTeam: "Barcelona", value: 6, sofifaId: "211517" },
  { name: "Rúben Dias", position: "DEF", country: "Portugal", clubTeam: "Man City", value: 6.5, sofifaId: "251706" },
  { name: "Raphaël Guerreiro", position: "DEF", country: "Portugal", clubTeam: "Bayern Munich", value: 5, sofifaId: "214135" },
  { name: "Nuno Mendes", position: "DEF", country: "Portugal", clubTeam: "PSG", value: 5.5, sofifaId: "264513" },
  { name: "João Palhinha", position: "MID", country: "Portugal", clubTeam: "Bayern Munich", value: 6, sofifaId: "241036" },
  { name: "Bruno Fernandes", position: "MID", country: "Portugal", clubTeam: "Man United", value: 7.5, sofifaId: "212831" },
  { name: "Bernardo Silva", position: "MID", country: "Portugal", clubTeam: "Man City", value: 7.5, sofifaId: "222433" },
  { name: "João Félix", position: "MID", country: "Portugal", clubTeam: "Chelsea", value: 6.5, sofifaId: "244747" },
  { name: "Cristiano Ronaldo", position: "FWD", country: "Portugal", clubTeam: "Al-Nassr", value: 7.5, sofifaId: "20801" },
  { name: "Rafael Leão", position: "FWD", country: "Portugal", clubTeam: "AC Milan", value: 8, sofifaId: "244696" },
  { name: "Gonçalo Ramos", position: "FWD", country: "Portugal", clubTeam: "PSG", value: 6.5, sofifaId: "263609" },

  // ===== NETHERLANDS =====
  { name: "Bart Verbruggen", position: "GK", country: "Netherlands", clubTeam: "Brighton", value: 4, sofifaId: "270030" },
  { name: "Virgil van Dijk", position: "DEF", country: "Netherlands", clubTeam: "Liverpool", value: 6.5, sofifaId: "203376" },
  { name: "Stefan de Vrij", position: "DEF", country: "Netherlands", clubTeam: "Inter Milan", value: 5, sofifaId: "194014" },
  { name: "Denzel Dumfries", position: "DEF", country: "Netherlands", clubTeam: "Inter Milan", value: 5.5, sofifaId: "228749" },
  { name: "Frenkie de Jong", position: "MID", country: "Netherlands", clubTeam: "Barcelona", value: 7.5, sofifaId: "240476" },
  { name: "Tijjani Reijnders", position: "MID", country: "Netherlands", clubTeam: "AC Milan", value: 6.5, sofifaId: "255866" },
  { name: "Xavi Simons", position: "MID", country: "Netherlands", clubTeam: "Leipzig", value: 7, sofifaId: "273331" },
  { name: "Teun Koopmeiners", position: "MID", country: "Netherlands", clubTeam: "Juventus", value: 6.5, sofifaId: "247440" },
  { name: "Cody Gakpo", position: "FWD", country: "Netherlands", clubTeam: "Liverpool", value: 7.5, sofifaId: "258004" },
  { name: "Memphis Depay", position: "FWD", country: "Netherlands", clubTeam: "Atletico Madrid", value: 5.5, sofifaId: "200563" },
  { name: "Donyell Malen", position: "FWD", country: "Netherlands", clubTeam: "Aston Villa", value: 6, sofifaId: "249380" },

  // ===== BELGIUM =====
  { name: "Thibaut Courtois", position: "GK", country: "Belgium", clubTeam: "Real Madrid", value: 5.5, sofifaId: "192448" },
  { name: "Timothy Castagne", position: "DEF", country: "Belgium", clubTeam: "Fulham", value: 4.5, sofifaId: "218218" },
  { name: "Jan Vertonghen", position: "DEF", country: "Belgium", clubTeam: "RSC Anderlecht", value: 4, sofifaId: "177092" },
  { name: "Wout Faes", position: "DEF", country: "Belgium", clubTeam: "Leicester", value: 4, sofifaId: "247424" },
  { name: "Kevin De Bruyne", position: "MID", country: "Belgium", clubTeam: "Man City", value: 9.5, sofifaId: "192985" },
  { name: "Youri Tielemans", position: "MID", country: "Belgium", clubTeam: "Aston Villa", value: 5.5, sofifaId: "218528" },
  { name: "Leandro Trossard", position: "MID", country: "Belgium", clubTeam: "Arsenal", value: 6, sofifaId: "231866" },
  { name: "Jérémy Doku", position: "MID", country: "Belgium", clubTeam: "Man City", value: 6.5, sofifaId: "264768" },
  { name: "Romelu Lukaku", position: "FWD", country: "Belgium", clubTeam: "Napoli", value: 6, sofifaId: "192505" },
  { name: "Lois Openda", position: "FWD", country: "Belgium", clubTeam: "Leipzig", value: 6.5, sofifaId: "258123" },
  { name: "Charles De Ketelaere", position: "MID", country: "Belgium", clubTeam: "Atalanta", value: 6, sofifaId: "256844" },

  // ===== ITALY =====
  { name: "Gianluigi Donnarumma", position: "GK", country: "Italy", clubTeam: "PSG", value: 5.5, sofifaId: "230666" },
  { name: "Giovanni Di Lorenzo", position: "DEF", country: "Italy", clubTeam: "Napoli", value: 5.5, sofifaId: "220455" },
  { name: "Alessandro Bastoni", position: "DEF", country: "Italy", clubTeam: "Inter Milan", value: 6, sofifaId: "244625" },
  { name: "Federico Dimarco", position: "DEF", country: "Italy", clubTeam: "Inter Milan", value: 5.5, sofifaId: "233515" },
  { name: "Nicolò Barella", position: "MID", country: "Italy", clubTeam: "Inter Milan", value: 6.5, sofifaId: "236459" },
  { name: "Sandro Tonali", position: "MID", country: "Italy", clubTeam: "Newcastle", value: 6.5, sofifaId: "248927" },
  { name: "Lorenzo Pellegrini", position: "MID", country: "Italy", clubTeam: "Roma", value: 5.5, sofifaId: "226460" },
  { name: "Federico Chiesa", position: "MID", country: "Italy", clubTeam: "Liverpool", value: 6.5, sofifaId: "233866" },
  { name: "Giacomo Raspadori", position: "FWD", country: "Italy", clubTeam: "Napoli", value: 6, sofifaId: "257049" },
  { name: "Gianluca Scamacca", position: "FWD", country: "Italy", clubTeam: "Atalanta", value: 6, sofifaId: "254618" },
  { name: "Mateo Retegui", position: "FWD", country: "Italy", clubTeam: "Atalanta", value: 6.5, sofifaId: "253710" },

  // ===== CROATIA =====
  { name: "Dominik Livaković", position: "GK", country: "Croatia", clubTeam: "Fenerbahce", value: 5, sofifaId: "222049" },
  { name: "Joško Gvardiol", position: "DEF", country: "Croatia", clubTeam: "Man City", value: 7, sofifaId: "261224" },
  { name: "Dejan Lovren", position: "DEF", country: "Croatia", clubTeam: "Lyon", value: 4, sofifaId: "188781" },
  { name: "Mateo Kovačić", position: "MID", country: "Croatia", clubTeam: "Man City", value: 6, sofifaId: "214613" },
  { name: "Luka Modrić", position: "MID", country: "Croatia", clubTeam: "Real Madrid", value: 6.5, sofifaId: "177003" },
  { name: "Ivan Perišić", position: "MID", country: "Croatia", clubTeam: "Hajduk Split", value: 5.5, sofifaId: "189597" },
  { name: "Nikola Vlašić", position: "MID", country: "Croatia", clubTeam: "Torino", value: 5.5, sofifaId: "241322" },
  { name: "Andrej Kramarić", position: "FWD", country: "Croatia", clubTeam: "Hoffenheim", value: 6, sofifaId: "207135" },
  { name: "Bruno Petković", position: "FWD", country: "Croatia", clubTeam: "Dinamo Zagreb", value: 5, sofifaId: "208618" },

  // ===== MOROCCO =====
  { name: "Yassine Bounou", position: "GK", country: "Morocco", clubTeam: "Al-Hilal", value: 5, sofifaId: "210764" },
  { name: "Achraf Hakimi", position: "DEF", country: "Morocco", clubTeam: "PSG", value: 7.5, sofifaId: "237907" },
  { name: "Romain Saiss", position: "DEF", country: "Morocco", clubTeam: "Besiktas", value: 4, sofifaId: "199521" },
  { name: "Nayef Aguerd", position: "DEF", country: "Morocco", clubTeam: "West Ham", value: 5, sofifaId: "236572" },
  { name: "Sofyan Amrabat", position: "MID", country: "Morocco", clubTeam: "Fiorentina", value: 5.5, sofifaId: "238793" },
  { name: "Azzedine Ounahi", position: "MID", country: "Morocco", clubTeam: "Marseille", value: 5.5, sofifaId: "265449" },
  { name: "Hakim Ziyech", position: "MID", country: "Morocco", clubTeam: "Galatasaray", value: 6, sofifaId: "221028" },
  { name: "Sofiane Boufal", position: "MID", country: "Morocco", clubTeam: "Angers", value: 5, sofifaId: "216284" },
  { name: "Youssef En-Nesyri", position: "FWD", country: "Morocco", clubTeam: "Fenerbahce", value: 6.5, sofifaId: "241624" },
  { name: "Abde Ezzalzouli", position: "FWD", country: "Morocco", clubTeam: "Betis", value: 5.5, sofifaId: "271186" },

  // ===== SENEGAL =====
  { name: "Édouard Mendy", position: "GK", country: "Senegal", clubTeam: "Al-Ahli", value: 4, sofifaId: "226192" },
  { name: "Kalidou Koulibaly", position: "DEF", country: "Senegal", clubTeam: "Al-Hilal", value: 5.5, sofifaId: "202952" },
  { name: "Ismail Jakobs", position: "DEF", country: "Senegal", clubTeam: "Monaco", value: 4, sofifaId: "254234" },
  { name: "Cheikhou Kouyaté", position: "MID", country: "Senegal", clubTeam: "Nottm Forest", value: 4, sofifaId: "201596" },
  { name: "Idrissa Gueye", position: "MID", country: "Senegal", clubTeam: "Everton", value: 5, sofifaId: "202108" },
  { name: "Ismaïla Sarr", position: "MID", country: "Senegal", clubTeam: "Crystal Palace", value: 6, sofifaId: "239553" },
  { name: "Sadio Mané", position: "FWD", country: "Senegal", clubTeam: "Al-Nassr", value: 6.5, sofifaId: "208722" },
  { name: "Boulaye Dia", position: "FWD", country: "Senegal", clubTeam: "Lazio", value: 5.5, sofifaId: "237862" },
  { name: "Nicolas Jackson", position: "FWD", country: "Senegal", clubTeam: "Chelsea", value: 6.5, sofifaId: "263617" },

  // ===== USA =====
  { name: "Matt Turner", position: "GK", country: "USA", clubTeam: "Crystal Palace", value: 4, sofifaId: "220487" },
  { name: "Sergiño Dest", position: "DEF", country: "USA", clubTeam: "PSV", value: 4.5, sofifaId: "254618" },
  { name: "Tim Ream", position: "DEF", country: "USA", clubTeam: "Fulham", value: 3.5, sofifaId: "191258" },
  { name: "Tyler Adams", position: "MID", country: "USA", clubTeam: "Bournemouth", value: 6, sofifaId: "245839" },
  { name: "Weston McKennie", position: "MID", country: "USA", clubTeam: "Juventus", value: 5.5, sofifaId: "243359" },
  { name: "Giovanni Reyna", position: "MID", country: "USA", clubTeam: "Dortmund", value: 5.5, sofifaId: "265514" },
  { name: "Christian Pulisic", position: "MID", country: "USA", clubTeam: "AC Milan", value: 6.5, sofifaId: "221025" },
  { name: "Folarin Balogun", position: "FWD", country: "USA", clubTeam: "Monaco", value: 5.5, sofifaId: "266955" },
  { name: "Josh Sargent", position: "FWD", country: "USA", clubTeam: "Norwich", value: 5, sofifaId: "256014" },
  { name: "Ricardo Pepi", position: "FWD", country: "USA", clubTeam: "PSV", value: 5.5, sofifaId: "263941" },

  // ===== MEXICO =====
  { name: "Guillermo Ochoa", position: "GK", country: "Mexico", clubTeam: "AZ Alkmaar", value: 4.5, sofifaId: "176572" },
  { name: "Jorge Sánchez", position: "DEF", country: "Mexico", clubTeam: "Porto", value: 4, sofifaId: "247779" },
  { name: "Héctor Moreno", position: "DEF", country: "Mexico", clubTeam: "Monterrey", value: 4, sofifaId: "197476" },
  { name: "Hirving Lozano", position: "MID", country: "Mexico", clubTeam: "PSV", value: 6, sofifaId: "228703" },
  { name: "Edson Álvarez", position: "MID", country: "Mexico", clubTeam: "West Ham", value: 6, sofifaId: "234549" },
  { name: "Alexis Vega", position: "MID", country: "Mexico", clubTeam: "Guadalajara", value: 5, sofifaId: "237476" },
  { name: "Raúl Jiménez", position: "FWD", country: "Mexico", clubTeam: "Fulham", value: 5.5, sofifaId: "201960" },
  { name: "Henry Martín", position: "FWD", country: "Mexico", clubTeam: "Club America", value: 5, sofifaId: "200985" },

  // ===== JAPAN =====
  { name: "Shuichi Gonda", position: "GK", country: "Japan", clubTeam: "Shimizu S-Pulse", value: 3.5, sofifaId: "200282" },
  { name: "Yuto Nagatomo", position: "DEF", country: "Japan", clubTeam: "FC Tokyo", value: 4, sofifaId: "192714" },
  { name: "Hiroki Sakai", position: "DEF", country: "Japan", clubTeam: "Urawa Reds", value: 4, sofifaId: "200281" },
  { name: "Takehiro Tomiyasu", position: "DEF", country: "Japan", clubTeam: "Arsenal", value: 5, sofifaId: "248798" },
  { name: "Wataru Endo", position: "MID", country: "Japan", clubTeam: "Liverpool", value: 5.5, sofifaId: "231595" },
  { name: "Ritsu Doan", position: "MID", country: "Japan", clubTeam: "Freiburg", value: 5.5, sofifaId: "238814" },
  { name: "Takumi Minamino", position: "MID", country: "Japan", clubTeam: "Monaco", value: 5.5, sofifaId: "228752" },
  { name: "Keito Nakamura", position: "MID", country: "Japan", clubTeam: "Reims", value: 5, sofifaId: "259701" },
  { name: "Takefusa Kubo", position: "MID", country: "Japan", clubTeam: "Real Sociedad", value: 6.5, sofifaId: "257669" },
  { name: "Kaoru Mitoma", position: "FWD", country: "Japan", clubTeam: "Brighton", value: 7, sofifaId: "256698" },
  { name: "Daichi Kamada", position: "MID", country: "Japan", clubTeam: "Crystal Palace", value: 5.5, sofifaId: "243354" },
  { name: "Ayase Ueda", position: "FWD", country: "Japan", clubTeam: "Feyenoord", value: 5, sofifaId: "246793" },

  // ===== SOUTH KOREA =====
  { name: "Kim Seung-gyu", position: "GK", country: "South Korea", clubTeam: "Vissel Kobe", value: 3.5, sofifaId: "206191" },
  { name: "Kim Min-jae", position: "DEF", country: "South Korea", clubTeam: "Bayern Munich", value: 6.5, sofifaId: "241607" },
  { name: "Lee Young-jun", position: "DEF", country: "South Korea", clubTeam: "Genk", value: 4, sofifaId: "260965" },
  { name: "Lee Jae-sung", position: "MID", country: "South Korea", clubTeam: "Mainz", value: 5, sofifaId: "241286" },
  { name: "Hwang In-beom", position: "MID", country: "South Korea", clubTeam: "Feyenoord", value: 5.5, sofifaId: "230703" },
  { name: "Kwon Chang-hoon", position: "MID", country: "South Korea", clubTeam: "Suwon", value: 4.5, sofifaId: "216993" },
  { name: "Son Heung-min", position: "FWD", country: "South Korea", clubTeam: "Tottenham", value: 7.5, sofifaId: "200643" },
  { name: "Hwang Hee-chan", position: "FWD", country: "South Korea", clubTeam: "Wolves", value: 5.5, sofifaId: "236313" },
  { name: "Cho Gue-sung", position: "FWD", country: "South Korea", clubTeam: "Jeonbuk", value: 5, sofifaId: "249625" },

  // ===== CANADA =====
  { name: "Maxime Crépeau", position: "GK", country: "Canada", clubTeam: "LAFC", value: 3.5, sofifaId: "237025" },
  { name: "Alphonso Davies", position: "DEF", country: "Canada", clubTeam: "Bayern Munich", value: 7.5, sofifaId: "251369" },
  { name: "Alistair Johnston", position: "DEF", country: "Canada", clubTeam: "Celtic", value: 4.5, sofifaId: "252843" },
  { name: "Richie Laryea", position: "DEF", country: "Canada", clubTeam: "Nottm Forest", value: 4, sofifaId: "246459" },
  { name: "Stephen Eustáquio", position: "MID", country: "Canada", clubTeam: "Porto", value: 5.5, sofifaId: "247891" },
  { name: "Jonathan Osorio", position: "MID", country: "Canada", clubTeam: "Toronto FC", value: 4.5, sofifaId: "222168" },
  { name: "Tajon Buchanan", position: "MID", country: "Canada", clubTeam: "Inter Milan", value: 5.5, sofifaId: "252009" },
  { name: "Jonathan David", position: "FWD", country: "Canada", clubTeam: "Lille", value: 7, sofifaId: "254849" },
  { name: "Cyle Larin", position: "FWD", country: "Canada", clubTeam: "Club Brugge", value: 5.5, sofifaId: "223093" },

  // ===== URUGUAY =====
  { name: "Sergio Rochet", position: "GK", country: "Uruguay", clubTeam: "Nacional", value: 4, sofifaId: "233614" },
  { name: "Ronald Araújo", position: "DEF", country: "Uruguay", clubTeam: "Barcelona", value: 6.5, sofifaId: "266959" },
  { name: "José María Giménez", position: "DEF", country: "Uruguay", clubTeam: "Atletico Madrid", value: 5, sofifaId: "211147" },
  { name: "Rodrigo Bentancur", position: "MID", country: "Uruguay", clubTeam: "Tottenham", value: 6, sofifaId: "238812" },
  { name: "Federico Valverde", position: "MID", country: "Uruguay", clubTeam: "Real Madrid", value: 7.5, sofifaId: "242371" },
  { name: "Giorgian De Arrascaeta", position: "MID", country: "Uruguay", clubTeam: "Flamengo", value: 6, sofifaId: "222403" },
  { name: "Darwin Núñez", position: "FWD", country: "Uruguay", clubTeam: "Liverpool", value: 7, sofifaId: "264476" },
  { name: "Luis Suárez", position: "FWD", country: "Uruguay", clubTeam: "Nacional", value: 4.5, sofifaId: "176580" },
  { name: "Facundo Torres", position: "FWD", country: "Uruguay", clubTeam: "Orlando City", value: 5.5, sofifaId: "261768" },

  // ===== COLOMBIA =====
  { name: "Camilo Vargas", position: "GK", country: "Colombia", clubTeam: "Atlas", value: 4, sofifaId: "215381" },
  { name: "Dávinson Sánchez", position: "DEF", country: "Colombia", clubTeam: "Galatasaray", value: 5, sofifaId: "228512" },
  { name: "Santiago Arias", position: "DEF", country: "Colombia", clubTeam: "Bayer Leverkusen", value: 4, sofifaId: "206277" },
  { name: "Wilmar Barrios", position: "MID", country: "Colombia", clubTeam: "Zenit", value: 5, sofifaId: "236310" },
  { name: "James Rodríguez", position: "MID", country: "Colombia", clubTeam: "Rayo Vallecano", value: 6, sofifaId: "193003" },
  { name: "Juan Cuadrado", position: "MID", country: "Colombia", clubTeam: "Inter Miami", value: 5, sofifaId: "191680" },
  { name: "Luis Díaz", position: "MID", country: "Colombia", clubTeam: "Liverpool", value: 7.5, sofifaId: "244725" },
  { name: "Rafael Santos Borré", position: "FWD", country: "Colombia", clubTeam: "Eintracht Frankfurt", value: 5.5, sofifaId: "235345" },
  { name: "Jhon Durán", position: "FWD", country: "Colombia", clubTeam: "Aston Villa", value: 6.5, sofifaId: "270428" },

  // ===== NIGERIA =====
  { name: "Stanley Nwabali", position: "GK", country: "Nigeria", clubTeam: "Chippa United", value: 3.5, sofifaId: "265124" },
  { name: "Kenneth Omeruo", position: "DEF", country: "Nigeria", clubTeam: "Kasimpasa", value: 4, sofifaId: "215826" },
  { name: "Calvin Bassey", position: "DEF", country: "Nigeria", clubTeam: "Fulham", value: 4.5, sofifaId: "258063" },
  { name: "Wilfred Ndidi", position: "MID", country: "Nigeria", clubTeam: "Leicester", value: 6, sofifaId: "236514" },
  { name: "Alex Iwobi", position: "MID", country: "Nigeria", clubTeam: "Fulham", value: 5.5, sofifaId: "225145" },
  { name: "Ademola Lookman", position: "MID", country: "Nigeria", clubTeam: "Atalanta", value: 6.5, sofifaId: "231575" },
  { name: "Samuel Chukwueze", position: "MID", country: "Nigeria", clubTeam: "AC Milan", value: 5.5, sofifaId: "249481" },
  { name: "Victor Osimhen", position: "FWD", country: "Nigeria", clubTeam: "Galatasaray", value: 8.5, sofifaId: "254064" },
  { name: "Taiwo Awoniyi", position: "FWD", country: "Nigeria", clubTeam: "Nottm Forest", value: 5.5, sofifaId: "240576" },

  // ===== ECUADOR =====
  { name: "Hernán Galíndez", position: "GK", country: "Ecuador", clubTeam: "Aucas", value: 3.5, sofifaId: "225476" },
  { name: "Piero Hincapié", position: "DEF", country: "Ecuador", clubTeam: "Bayer Leverkusen", value: 5.5, sofifaId: "263614" },
  { name: "Byron Castillo", position: "DEF", country: "Ecuador", clubTeam: "Liga de Quito", value: 4, sofifaId: "261243" },
  { name: "Moisés Caicedo", position: "MID", country: "Ecuador", clubTeam: "Chelsea", value: 8, sofifaId: "259757" },
  { name: "Gonzalo Plata", position: "MID", country: "Ecuador", clubTeam: "Valladolid", value: 5.5, sofifaId: "260778" },
  { name: "Ángel Mena", position: "MID", country: "Ecuador", clubTeam: "León", value: 4.5, sofifaId: "208649" },
  { name: "Enner Valencia", position: "FWD", country: "Ecuador", clubTeam: "Fenerbahce", value: 5, sofifaId: "202535" },
  { name: "Kevin Rodríguez", position: "FWD", country: "Ecuador", clubTeam: "Ipswich", value: 5.5, sofifaId: "265134" },

  // ===== POLAND =====
  { name: "Wojciech Szczęsny", position: "GK", country: "Poland", clubTeam: "Barcelona", value: 5, sofifaId: "189615" },
  { name: "Jan Bednarek", position: "DEF", country: "Poland", clubTeam: "Southampton", value: 4.5, sofifaId: "220906" },
  { name: "Bartosz Bereszyński", position: "DEF", country: "Poland", clubTeam: "Empoli", value: 4, sofifaId: "213173" },
  { name: "Piotr Zieliński", position: "MID", country: "Poland", clubTeam: "Inter Milan", value: 6, sofifaId: "210573" },
  { name: "Przemysław Frankowski", position: "MID", country: "Poland", clubTeam: "Lens", value: 5, sofifaId: "238782" },
  { name: "Sebastian Szymański", position: "MID", country: "Poland", clubTeam: "Fenerbahce", value: 5.5, sofifaId: "246481" },
  { name: "Robert Lewandowski", position: "FWD", country: "Poland", clubTeam: "Barcelona", value: 8, sofifaId: "188545" },
  { name: "Arkadiusz Milik", position: "FWD", country: "Poland", clubTeam: "Juventus", value: 5.5, sofifaId: "215042" },
  { name: "Karol Swiderski", position: "FWD", country: "Poland", clubTeam: "Charlotte FC", value: 4.5, sofifaId: "241628" },

  // ===== DENMARK =====
  { name: "Kasper Schmeichel", position: "GK", country: "Denmark", clubTeam: "Anderlecht", value: 4.5, sofifaId: "184832" },
  { name: "Andreas Christensen", position: "DEF", country: "Denmark", clubTeam: "Barcelona", value: 5.5, sofifaId: "214847" },
  { name: "Simon Kjaer", position: "DEF", country: "Denmark", clubTeam: "AC Milan", value: 4.5, sofifaId: "194039" },
  { name: "Christian Eriksen", position: "MID", country: "Denmark", clubTeam: "Man United", value: 6.5, sofifaId: "197589" },
  { name: "Pierre-Emile Höjbjerg", position: "MID", country: "Denmark", clubTeam: "Marseille", value: 5.5, sofifaId: "216945" },
  { name: "Mikkel Damsgaard", position: "MID", country: "Denmark", clubTeam: "Brentford", value: 6, sofifaId: "255785" },
  { name: "Rasmus Hojlund", position: "FWD", country: "Denmark", clubTeam: "Man United", value: 7, sofifaId: "269971" },
  { name: "Jonas Wind", position: "FWD", country: "Denmark", clubTeam: "Wolfsburg", value: 5.5, sofifaId: "248912" },

  // ===== SWITZERLAND =====
  { name: "Yann Sommer", position: "GK", country: "Switzerland", clubTeam: "Inter Milan", value: 4.5, sofifaId: "196768" },
  { name: "Manuel Akanji", position: "DEF", country: "Switzerland", clubTeam: "Man City", value: 5.5, sofifaId: "222320" },
  { name: "Nico Elvedi", position: "DEF", country: "Switzerland", clubTeam: "Mönchengladbach", value: 4.5, sofifaId: "228682" },
  { name: "Granit Xhaka", position: "MID", country: "Switzerland", clubTeam: "Bayer Leverkusen", value: 6, sofifaId: "205658" },
  { name: "Xherdan Shaqiri", position: "MID", country: "Switzerland", clubTeam: "Chicago Fire", value: 5, sofifaId: "193677" },
  { name: "Remo Freuler", position: "MID", country: "Switzerland", clubTeam: "Nottm Forest", value: 5.5, sofifaId: "210518" },
  { name: "Ruben Vargas", position: "MID", country: "Switzerland", clubTeam: "Augsburg", value: 5.5, sofifaId: "248888" },
  { name: "Breel Embolo", position: "FWD", country: "Switzerland", clubTeam: "Monaco", value: 5.5, sofifaId: "226398" },
  { name: "Noah Okafor", position: "FWD", country: "Switzerland", clubTeam: "AC Milan", value: 5.5, sofifaId: "258053" },

  // ===== EGYPT =====
  { name: "Mohamed El-Shenawy", position: "GK", country: "Egypt", clubTeam: "Al-Ahly", value: 4, sofifaId: "208285" },
  { name: "Ahmed Hegazi", position: "DEF", country: "Egypt", clubTeam: "Al-Ittihad", value: 4, sofifaId: "206313" },
  { name: "Mohamed Elneny", position: "MID", country: "Egypt", clubTeam: "Arsenal", value: 5, sofifaId: "205807" },
  { name: "Omar Marmoush", position: "FWD", country: "Egypt", clubTeam: "Man City", value: 7.5, sofifaId: "243359" },
  { name: "Mohamed Salah", position: "FWD", country: "Egypt", clubTeam: "Liverpool", value: 9, sofifaId: "209331" },
  { name: "Trezeguet", position: "MID", country: "Egypt", clubTeam: "Kasimpasa", value: 4.5, sofifaId: "219722" },

  // ===== CAMEROON =====
  { name: "André Onana", position: "GK", country: "Cameroon", clubTeam: "Man United", value: 5.5, sofifaId: "231488" },
  { name: "Collins Fai", position: "DEF", country: "Cameroon", clubTeam: "Al-Tai", value: 4, sofifaId: "209282" },
  { name: "Nicolas Nkoulou", position: "DEF", country: "Cameroon", clubTeam: "Verona", value: 4, sofifaId: "193018" },
  { name: "Frank Anguissa", position: "MID", country: "Cameroon", clubTeam: "Napoli", value: 6.5, sofifaId: "230921" },
  { name: "Karl Toko Ekambi", position: "MID", country: "Cameroon", clubTeam: "Al-Qadsiah", value: 5.5, sofifaId: "224367" },
  { name: "Bryan Mbeumo", position: "MID", country: "Cameroon", clubTeam: "Brentford", value: 6.5, sofifaId: "252571" },
  { name: "Eric Maxim Choupo-Moting", position: "FWD", country: "Cameroon", clubTeam: "Eintracht Frankfurt", value: 5, sofifaId: "198695" },

  // ===== GHANA =====
  { name: "Lawrence Ati-Zigi", position: "GK", country: "Ghana", clubTeam: "St. Gallen", value: 3.5, sofifaId: "236988" },
  { name: "Daniel Amartey", position: "DEF", country: "Ghana", clubTeam: "Besiktas", value: 4, sofifaId: "211027" },
  { name: "Thomas Partey", position: "MID", country: "Ghana", clubTeam: "Arsenal", value: 6, sofifaId: "210462" },
  { name: "Mohammed Kudus", position: "MID", country: "Ghana", clubTeam: "West Ham", value: 6.5, sofifaId: "266973" },
  { name: "Jordan Ayew", position: "FWD", country: "Ghana", clubTeam: "Crystal Palace", value: 5, sofifaId: "212131" },
  { name: "Inaki Williams", position: "FWD", country: "Ghana", clubTeam: "Athletic Bilbao", value: 5.5, sofifaId: "226161" },
  { name: "Antoine Semenyo", position: "FWD", country: "Ghana", clubTeam: "Bournemouth", value: 5.5, sofifaId: "263479" },

  // ===== SERBIA =====
  { name: "Predrag Rajković", position: "GK", country: "Serbia", clubTeam: "Real Mallorca", value: 4, sofifaId: "220906" },
  { name: "Strahinja Milenkovic", position: "DEF", country: "Serbia", clubTeam: "Nottm Forest", value: 5.5, sofifaId: "237929" },
  { name: "Dušan Tadić", position: "MID", country: "Serbia", clubTeam: "Fenerbahce", value: 5.5, sofifaId: "204475" },
  { name: "Sergej Milinković-Savić", position: "MID", country: "Serbia", clubTeam: "Al-Hilal", value: 6.5, sofifaId: "217104" },
  { name: "Sasa Lukic", position: "MID", country: "Serbia", clubTeam: "Fulham", value: 5, sofifaId: "233851" },
  { name: "Dušan Vlahović", position: "FWD", country: "Serbia", clubTeam: "Juventus", value: 8, sofifaId: "252879" },
  { name: "Luka Jović", position: "FWD", country: "Serbia", clubTeam: "AC Milan", value: 5.5, sofifaId: "236095" },

  // ===== IRAN =====
  { name: "Alireza Beiranvand", position: "GK", country: "Iran", clubTeam: "Persepolis", value: 3.5, sofifaId: "218694" },
  { name: "Milad Mohammadi", position: "DEF", country: "Iran", clubTeam: "AEK Athens", value: 4, sofifaId: "214849" },
  { name: "Saman Ghoddos", position: "MID", country: "Iran", clubTeam: "Brentford", value: 5, sofifaId: "225060" },
  { name: "Alireza Jahanbakhsh", position: "MID", country: "Iran", clubTeam: "Feyenoord", value: 5.5, sofifaId: "220629" },
  { name: "Sardar Azmoun", position: "FWD", country: "Iran", clubTeam: "Bayer Leverkusen", value: 6, sofifaId: "218887" },
  { name: "Mehdi Taremi", position: "FWD", country: "Iran", clubTeam: "Inter Milan", value: 6.5, sofifaId: "219975" },

  // ===== AUSTRALIA =====
  { name: "Mathew Ryan", position: "GK", country: "Australia", clubTeam: "AZ Alkmaar", value: 4, sofifaId: "200048" },
  { name: "Aziz Behich", position: "DEF", country: "Australia", clubTeam: "Dundee United", value: 4, sofifaId: "203048" },
  { name: "Harry Souttar", position: "DEF", country: "Australia", clubTeam: "Leicester", value: 4.5, sofifaId: "247218" },
  { name: "Aaron Mooy", position: "MID", country: "Australia", clubTeam: "Celtic", value: 5, sofifaId: "206617" },
  { name: "Jackson Irvine", position: "MID", country: "Australia", clubTeam: "St. Pauli", value: 4.5, sofifaId: "214640" },
  { name: "Mathew Leckie", position: "MID", country: "Australia", clubTeam: "Melbourne City", value: 4.5, sofifaId: "192930" },
  { name: "Mitchell Duke", position: "FWD", country: "Australia", clubTeam: "Fagiano Okayama", value: 4.5, sofifaId: "214093" },
  { name: "Adam Maclaren", position: "FWD", country: "Australia", clubTeam: "Melbourne City", value: 4, sofifaId: "221780" },

  // ===== IVORY COAST =====
  { name: "Yahia Fofana", position: "GK", country: "Ivory Coast", clubTeam: "Chelsea", value: 4.5, sofifaId: "244786" },
  { name: "Eric Bailly", position: "DEF", country: "Ivory Coast", clubTeam: "Besiktas", value: 4.5, sofifaId: "211831" },
  { name: "Franck Kessié", position: "MID", country: "Ivory Coast", clubTeam: "Al-Ahli", value: 6, sofifaId: "225326" },
  { name: "Sébastien Haller", position: "FWD", country: "Ivory Coast", clubTeam: "Dortmund", value: 6, sofifaId: "217680" },
  { name: "Nicolas Pépé", position: "MID", country: "Ivory Coast", clubTeam: "Trabzonspor", value: 5.5, sofifaId: "225044" },
  { name: "Simon Adingra", position: "MID", country: "Ivory Coast", clubTeam: "Brighton", value: 5.5, sofifaId: "270428" },
  { name: "Wilfried Zaha", position: "MID", country: "Ivory Coast", clubTeam: "Galatasaray", value: 5.5, sofifaId: "201862" },
];

const gameweeks = [
  { number: 1, name: "Group Stage — Round 1", deadline: new Date("2026-06-11T12:00:00Z") },
  { number: 2, name: "Group Stage — Round 2", deadline: new Date("2026-06-17T12:00:00Z") },
  { number: 3, name: "Group Stage — Round 3", deadline: new Date("2026-06-23T12:00:00Z") },
  { number: 4, name: "Round of 32", deadline: new Date("2026-06-29T12:00:00Z") },
  { number: 5, name: "Round of 16", deadline: new Date("2026-07-04T12:00:00Z") },
  { number: 6, name: "Quarter-Finals", deadline: new Date("2026-07-09T12:00:00Z") },
  { number: 7, name: "Semi-Finals", deadline: new Date("2026-07-14T12:00:00Z") },
  { number: 8, name: "Final", deadline: new Date("2026-07-19T12:00:00Z") },
];

const extraPlayers = [
  // ===== AUSTRIA =====
  { name: "Patrick Pentz", position: "GK", country: "Austria", clubTeam: "Bayer Leverkusen", value: 4.5 },
  { name: "Alexander Schlager", position: "GK", country: "Austria", clubTeam: "Schalke", value: 3.5 },
  { name: "David Alaba", position: "DEF", country: "Austria", clubTeam: "Real Madrid", value: 8.0 },
  { name: "Philipp Lienhart", position: "DEF", country: "Austria", clubTeam: "Freiburg", value: 5.0 },
  { name: "Stefan Posch", position: "DEF", country: "Austria", clubTeam: "Bologna", value: 5.0 },
  { name: "Maximilian Wöber", position: "DEF", country: "Austria", clubTeam: "Leeds", value: 4.5 },
  { name: "Christopher Trimmel", position: "DEF", country: "Austria", clubTeam: "Union Berlin", value: 4.0 },
  { name: "Flavius Daniliuc", position: "DEF", country: "Austria", clubTeam: "Salernitana", value: 4.0 },
  { name: "Marcel Sabitzer", position: "MID", country: "Austria", clubTeam: "Dortmund", value: 7.5 },
  { name: "Konrad Laimer", position: "MID", country: "Austria", clubTeam: "Bayern Munich", value: 7.5 },
  { name: "Florian Grillitsch", position: "MID", country: "Austria", clubTeam: "Ajax", value: 5.5 },
  { name: "Nicolas Seiwald", position: "MID", country: "Austria", clubTeam: "Leipzig", value: 6.5 },
  { name: "Christoph Baumgartner", position: "MID", country: "Austria", clubTeam: "Leipzig", value: 6.5 },
  { name: "Florian Kainz", position: "MID", country: "Austria", clubTeam: "FC Köln", value: 5.5 },
  { name: "Romano Schmid", position: "MID", country: "Austria", clubTeam: "Werder Bremen", value: 5.0 },
  { name: "Patrick Wimmer", position: "MID", country: "Austria", clubTeam: "Wolfsburg", value: 5.0 },
  { name: "Michael Gregoritsch", position: "FWD", country: "Austria", clubTeam: "Freiburg", value: 6.0 },
  { name: "Marko Arnautovic", position: "FWD", country: "Austria", clubTeam: "Inter Milan", value: 6.5 },
  { name: "Andreas Weimann", position: "FWD", country: "Austria", clubTeam: "Bristol City", value: 4.5 },
  { name: "Sasa Kalajdzic", position: "FWD", country: "Austria", clubTeam: "Wolves", value: 5.0 },
  { name: "Junior Adamu", position: "FWD", country: "Austria", clubTeam: "Freiburg", value: 4.0 },
  { name: "Karim Adeyemi", position: "FWD", country: "Austria", clubTeam: "Dortmund", value: 7.0 },

  // ===== TURKEY =====
  { name: "Altay Bayındır", position: "GK", country: "Turkey", clubTeam: "Man United", value: 5.0 },
  { name: "Uğurcan Çakır", position: "GK", country: "Turkey", clubTeam: "Trabzonspor", value: 4.0 },
  { name: "Merih Demiral", position: "DEF", country: "Turkey", clubTeam: "Al-Ahli", value: 6.0 },
  { name: "Abdülkerim Bardakcı", position: "DEF", country: "Turkey", clubTeam: "Galatasaray", value: 5.0 },
  { name: "Zeki Çelik", position: "DEF", country: "Turkey", clubTeam: "Roma", value: 5.5 },
  { name: "Ferdi Kadıoğlu", position: "DEF", country: "Turkey", clubTeam: "Brighton", value: 5.5 },
  { name: "Samet Akaydın", position: "DEF", country: "Turkey", clubTeam: "Fenerbahce", value: 4.0 },
  { name: "Mert Müldür", position: "DEF", country: "Turkey", clubTeam: "Atalanta", value: 4.5 },
  { name: "Hakan Çalhanoğlu", position: "MID", country: "Turkey", clubTeam: "Inter Milan", value: 8.5 },
  { name: "Arda Güler", position: "MID", country: "Turkey", clubTeam: "Real Madrid", value: 8.0 },
  { name: "Kaan Ayhan", position: "MID", country: "Turkey", clubTeam: "Galatasaray", value: 5.5 },
  { name: "Orkun Kökçü", position: "MID", country: "Turkey", clubTeam: "Benfica", value: 6.5 },
  { name: "Salih Özcan", position: "MID", country: "Turkey", clubTeam: "Dortmund", value: 5.5 },
  { name: "İrfan Can Kahveci", position: "MID", country: "Turkey", clubTeam: "Fenerbahce", value: 5.5 },
  { name: "Kerem Aktürkoğlu", position: "MID", country: "Turkey", clubTeam: "Galatasaray", value: 6.5 },
  { name: "Dorukhan Toköz", position: "MID", country: "Turkey", clubTeam: "Trabzonspor", value: 4.5 },
  { name: "Cenk Tosun", position: "FWD", country: "Turkey", clubTeam: "Beşiktaş", value: 4.5 },
  { name: "Burak Yılmaz", position: "FWD", country: "Turkey", clubTeam: "Adana Demirspor", value: 4.0 },
  { name: "Cengiz Ünder", position: "FWD", country: "Turkey", clubTeam: "Fenerbahce", value: 6.0 },
  { name: "Yusuf Yazıcı", position: "FWD", country: "Turkey", clubTeam: "LOSC Lille", value: 6.5 },
  { name: "Baris Alper Yilmaz", position: "FWD", country: "Turkey", clubTeam: "Galatasaray", value: 6.0 },
  { name: "Serdar Dursun", position: "FWD", country: "Turkey", clubTeam: "Darmstadt", value: 4.0 },

  // ===== SCOTLAND =====
  { name: "Angus Gunn", position: "GK", country: "Scotland", clubTeam: "Norwich", value: 4.0 },
  { name: "Craig Gordon", position: "GK", country: "Scotland", clubTeam: "Hearts", value: 3.5 },
  { name: "Andrew Robertson", position: "DEF", country: "Scotland", clubTeam: "Liverpool", value: 7.5 },
  { name: "Kieran Tierney", position: "DEF", country: "Scotland", clubTeam: "Real Sociedad", value: 6.0 },
  { name: "Grant Hanley", position: "DEF", country: "Scotland", clubTeam: "Norwich", value: 4.0 },
  { name: "Jack Hendry", position: "DEF", country: "Scotland", clubTeam: "Club Brugge", value: 5.0 },
  { name: "Aaron Hickey", position: "DEF", country: "Scotland", clubTeam: "Brentford", value: 5.5 },
  { name: "Greg Taylor", position: "DEF", country: "Scotland", clubTeam: "Celtic", value: 4.5 },
  { name: "Scott McTominay", position: "MID", country: "Scotland", clubTeam: "Napoli", value: 7.5 },
  { name: "Callum McGregor", position: "MID", country: "Scotland", clubTeam: "Celtic", value: 6.0 },
  { name: "Billy Gilmour", position: "MID", country: "Scotland", clubTeam: "Brighton", value: 6.5 },
  { name: "Ryan Christie", position: "MID", country: "Scotland", clubTeam: "Bournemouth", value: 5.5 },
  { name: "John McGinn", position: "MID", country: "Scotland", clubTeam: "Aston Villa", value: 7.0 },
  { name: "Stuart Armstrong", position: "MID", country: "Scotland", clubTeam: "Southampton", value: 5.0 },
  { name: "Ryan Jack", position: "MID", country: "Scotland", clubTeam: "Rangers", value: 4.5 },
  { name: "Lewis Ferguson", position: "MID", country: "Scotland", clubTeam: "Bologna", value: 5.5 },
  { name: "Lyndon Dykes", position: "FWD", country: "Scotland", clubTeam: "QPR", value: 5.0 },
  { name: "Che Adams", position: "FWD", country: "Scotland", clubTeam: "Torino", value: 5.5 },
  { name: "Ryan Fraser", position: "FWD", country: "Scotland", clubTeam: "Newcastle", value: 5.0 },
  { name: "Lawrence Shankland", position: "FWD", country: "Scotland", clubTeam: "Hearts", value: 5.0 },
  { name: "Kenny McLean", position: "MID", country: "Scotland", clubTeam: "Norwich", value: 4.0 },
  { name: "Liam Scales", position: "DEF", country: "Scotland", clubTeam: "Celtic", value: 4.0 },

  // ===== CHILE =====
  { name: "Claudio Bravo", position: "GK", country: "Chile", clubTeam: "Real Betis", value: 4.0 },
  { name: "Gabriel Arias", position: "GK", country: "Chile", clubTeam: "Racing Club", value: 3.5 },
  { name: "Guillermo Maripán", position: "DEF", country: "Chile", clubTeam: "Monaco", value: 5.5 },
  { name: "Mauricio Isla", position: "DEF", country: "Chile", clubTeam: "Fluminense", value: 4.0 },
  { name: "Paulo Díaz", position: "DEF", country: "Chile", clubTeam: "LA Galaxy", value: 4.5 },
  { name: "Sebastián Vegas", position: "DEF", country: "Chile", clubTeam: "Monterrey", value: 4.0 },
  { name: "Gabriel Suazo", position: "DEF", country: "Chile", clubTeam: "Toulouse", value: 4.5 },
  { name: "Clemente Montes", position: "DEF", country: "Chile", clubTeam: "Colo-Colo", value: 4.0 },
  { name: "Arturo Vidal", position: "MID", country: "Chile", clubTeam: "Colo-Colo", value: 5.0 },
  { name: "Charles Aránguiz", position: "MID", country: "Chile", clubTeam: "Bayer Leverkusen", value: 5.5 },
  { name: "Erick Pulgar", position: "MID", country: "Chile", clubTeam: "Flamengo", value: 5.5 },
  { name: "Diego Valdés", position: "MID", country: "Chile", clubTeam: "Club América", value: 5.0 },
  { name: "Marcelino Núñez", position: "MID", country: "Chile", clubTeam: "Norwich", value: 5.5 },
  { name: "Rodrigo Echeverría", position: "MID", country: "Chile", clubTeam: "Huachipato", value: 4.0 },
  { name: "Víctor Dávila", position: "MID", country: "Chile", clubTeam: "CSKA Moscow", value: 5.0 },
  { name: "César Pinares", position: "MID", country: "Chile", clubTeam: "Granada", value: 4.0 },
  { name: "Alexis Sánchez", position: "FWD", country: "Chile", clubTeam: "Inter Milan", value: 7.0 },
  { name: "Eduardo Vargas", position: "FWD", country: "Chile", clubTeam: "Atlético Mineiro", value: 5.0 },
  { name: "Ben Brereton Díaz", position: "FWD", country: "Chile", clubTeam: "Real Sociedad", value: 6.0 },
  { name: "Joaquín Montecinos", position: "FWD", country: "Chile", clubTeam: "Independiente", value: 4.5 },
  { name: "Bryan Carrasco", position: "FWD", country: "Chile", clubTeam: "Talleres", value: 4.0 },
  { name: "Iván Morales", position: "FWD", country: "Chile", clubTeam: "Colo-Colo", value: 4.0 },

  // ===== SOUTH AFRICA =====
  { name: "Ronwen Williams", position: "GK", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 4.5 },
  { name: "Veli Mothwa", position: "GK", country: "South Africa", clubTeam: "AmaZulu", value: 3.5 },
  { name: "Siyanda Xulu", position: "DEF", country: "South Africa", clubTeam: "Kasımpaşa", value: 4.5 },
  { name: "Reeve Frosler", position: "DEF", country: "South Africa", clubTeam: "Kaizer Chiefs", value: 4.0 },
  { name: "Terrence Mashego", position: "DEF", country: "South Africa", clubTeam: "Cape Town City", value: 4.0 },
  { name: "Rushine De Reuck", position: "DEF", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 4.0 },
  { name: "Ramahlwe Mphahlele", position: "DEF", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 4.0 },
  { name: "Mothobi Mvala", position: "MID", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 5.0 },
  { name: "Themba Zwane", position: "MID", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 5.0 },
  { name: "Bongani Zungu", position: "MID", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 5.0 },
  { name: "Ethan Nkosi", position: "MID", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 4.5 },
  { name: "Lyle Foster", position: "FWD", country: "South Africa", clubTeam: "Burnley", value: 6.0 },
  { name: "Percy Tau", position: "FWD", country: "South Africa", clubTeam: "Al-Ahly", value: 5.5 },
  { name: "Teboho Mokoena", position: "MID", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 5.5 },
  { name: "Njabulo Blom", position: "MID", country: "South Africa", clubTeam: "St Louis City", value: 4.5 },
  { name: "Sifiso Hlanti", position: "DEF", country: "South Africa", clubTeam: "Kaizer Chiefs", value: 3.5 },
  { name: "Nkosinathi Sibisi", position: "DEF", country: "South Africa", clubTeam: "Orlando Pirates", value: 4.0 },
  { name: "Sphephelo Sithole", position: "DEF", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 4.0 },
  { name: "Keagan Dolly", position: "FWD", country: "South Africa", clubTeam: "Kaizer Chiefs", value: 5.0 },
  { name: "Evidence Makgopa", position: "FWD", country: "South Africa", clubTeam: "Orlando Pirates", value: 4.5 },
  { name: "Bradley Cross", position: "DEF", country: "South Africa", clubTeam: "Mamelodi Sundowns", value: 3.5 },
  { name: "Fawaaz Basadien", position: "DEF", country: "South Africa", clubTeam: "Cape Town City", value: 3.5 },

  // ===== ALGERIA =====
  { name: "Raïs M'Bolhi", position: "GK", country: "Algeria", clubTeam: "Al-Ettifaq", value: 4.5 },
  { name: "Alexandre Oukidja", position: "GK", country: "Algeria", clubTeam: "Metz", value: 3.5 },
  { name: "Ramy Bensebaïni", position: "DEF", country: "Algeria", clubTeam: "Dortmund", value: 6.0 },
  { name: "Aissa Mandi", position: "DEF", country: "Algeria", clubTeam: "Villarreal", value: 5.0 },
  { name: "Djamel Benlamri", position: "DEF", country: "Algeria", clubTeam: "Lyon", value: 4.5 },
  { name: "Mehdi Zeffane", position: "DEF", country: "Algeria", clubTeam: "Rennes", value: 4.5 },
  { name: "Youcef Atal", position: "DEF", country: "Algeria", clubTeam: "Nice", value: 5.5 },
  { name: "Adam Ounas", position: "MID", country: "Algeria", clubTeam: "Nice", value: 6.0 },
  { name: "Ismaïl Bennacer", position: "MID", country: "Algeria", clubTeam: "AC Milan", value: 7.0 },
  { name: "Adlène Guedioura", position: "MID", country: "Algeria", clubTeam: "Nottm Forest", value: 4.0 },
  { name: "Sofiane Feghouli", position: "MID", country: "Algeria", clubTeam: "Al-Ittihad", value: 5.0 },
  { name: "Ramiz Zerrouki", position: "MID", country: "Algeria", clubTeam: "Twente", value: 5.0 },
  { name: "Mehdi Tahrat", position: "MID", country: "Algeria", clubTeam: "Châteauroux", value: 4.0 },
  { name: "Samir Beloufa", position: "MID", country: "Algeria", clubTeam: "Zamalek", value: 3.5 },
  { name: "Houssem Aouar", position: "MID", country: "Algeria", clubTeam: "Lyon", value: 6.5 },
  { name: "Riyad Mahrez", position: "MID", country: "Algeria", clubTeam: "Al-Ahli", value: 8.0 },
  { name: "Islam Slimani", position: "FWD", country: "Algeria", clubTeam: "Brest", value: 5.0 },
  { name: "Baghdad Bounedjah", position: "FWD", country: "Algeria", clubTeam: "Al-Sadd", value: 4.5 },
  { name: "Yacine Brahimi", position: "FWD", country: "Algeria", clubTeam: "Al-Rayyan", value: 5.5 },
  { name: "Andy Delort", position: "FWD", country: "Algeria", clubTeam: "Nice", value: 6.0 },
  { name: "Dzyuba lookalike", position: "FWD", country: "Algeria", clubTeam: "Shakhtar", value: 4.0 },
  { name: "Anis Harit", position: "MID", country: "Algeria", clubTeam: "Marseille", value: 5.5 },

  // ===== SAUDI ARABIA =====
  { name: "Mohammed Al-Owais", position: "GK", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 5.0 },
  { name: "Fawaz Al-Qarni", position: "GK", country: "Saudi Arabia", clubTeam: "Al-Shabab", value: 3.5 },
  { name: "Ali Al-Bulayhi", position: "DEF", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 5.0 },
  { name: "Yasser Al-Shahrani", position: "DEF", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 4.5 },
  { name: "Abdulelah Al-Amri", position: "DEF", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 4.0 },
  { name: "Sultan Al-Ghannam", position: "DEF", country: "Saudi Arabia", clubTeam: "Al-Nassr", value: 4.0 },
  { name: "Mohammed Al-Breik", position: "DEF", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 4.0 },
  { name: "Hassan Al-Tambakti", position: "DEF", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 4.5 },
  { name: "Riyadh Sharahili", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 4.5 },
  { name: "Mohammed Kanno", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 5.0 },
  { name: "Sami Al-Najei", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Ettifaq", value: 4.0 },
  { name: "Nasser Al-Dawsari", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 6.0 },
  { name: "Hattan Bahebri", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Shabab", value: 4.5 },
  { name: "Abdulrahman Al-Obood", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 4.0 },
  { name: "Salem Al-Dawsari", position: "MID", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 6.5 },
  { name: "Saud Abdulhamid", position: "DEF", country: "Saudi Arabia", clubTeam: "Roma", value: 5.0 },
  { name: "Firas Al-Buraikan", position: "FWD", country: "Saudi Arabia", clubTeam: "Al-Ahli", value: 6.0 },
  { name: "Saleh Al-Shehri", position: "FWD", country: "Saudi Arabia", clubTeam: "Al-Hilal", value: 6.0 },
  { name: "Abdullah Al-Hamdan", position: "FWD", country: "Saudi Arabia", clubTeam: "Al-Shabab", value: 5.5 },
  { name: "Mousa Al-Taamari", position: "FWD", country: "Saudi Arabia", clubTeam: "Montpellier", value: 5.5 },
  { name: "Yehya Al-Shehri", position: "FWD", country: "Saudi Arabia", clubTeam: "Al-Nassr", value: 4.5 },
  { name: "Musab Al-Juwayr", position: "FWD", country: "Saudi Arabia", clubTeam: "Al-Nassr", value: 4.0 },

  // ===== QATAR =====
  { name: "Meshaal Barsham", position: "GK", country: "Qatar", clubTeam: "Al-Sadd", value: 4.5 },
  { name: "Saad Al Sheeb", position: "GK", country: "Qatar", clubTeam: "Al-Sadd", value: 4.0 },
  { name: "Pedro Miguel", position: "DEF", country: "Qatar", clubTeam: "Al-Gharafa", value: 4.5 },
  { name: "Bassam Al-Rawi", position: "DEF", country: "Qatar", clubTeam: "Al-Rayyan", value: 4.0 },
  { name: "Tarek Salman", position: "DEF", country: "Qatar", clubTeam: "Al-Sadd", value: 3.5 },
  { name: "Abdelkarim Hassan", position: "DEF", country: "Qatar", clubTeam: "Al-Sadd", value: 4.5 },
  { name: "Homam Ahmed", position: "DEF", country: "Qatar", clubTeam: "Al-Sadd", value: 4.0 },
  { name: "Musab Kheder", position: "MID", country: "Qatar", clubTeam: "Al-Sadd", value: 5.0 },
  { name: "Karim Boudiaf", position: "MID", country: "Qatar", clubTeam: "Al-Duhail", value: 5.0 },
  { name: "Salem Al-Hajri", position: "MID", country: "Qatar", clubTeam: "Al-Sadd", value: 4.5 },
  { name: "Assim Madibo", position: "MID", country: "Qatar", clubTeam: "Dallas FC", value: 5.0 },
  { name: "Ali Asad", position: "MID", country: "Qatar", clubTeam: "Al-Gharafa", value: 4.0 },
  { name: "Mohammed Waad", position: "MID", country: "Qatar", clubTeam: "Al-Sadd", value: 4.0 },
  { name: "Ahmed Suhail", position: "MID", country: "Qatar", clubTeam: "Al-Duhail", value: 3.5 },
  { name: "Hassan Al-Haydos", position: "MID", country: "Qatar", clubTeam: "Al-Sadd", value: 6.0 },
  { name: "Hamid Ismail", position: "DEF", country: "Qatar", clubTeam: "Al-Rayyan", value: 3.5 },
  { name: "Almoez Ali", position: "FWD", country: "Qatar", clubTeam: "Al-Duhail", value: 7.0 },
  { name: "Akram Afif", position: "FWD", country: "Qatar", clubTeam: "Al-Sadd", value: 7.0 },
  { name: "Ismaeel Mohammad", position: "FWD", country: "Qatar", clubTeam: "Al-Sadd", value: 5.0 },
  { name: "Mohammed Muntari", position: "FWD", country: "Qatar", clubTeam: "Al-Duhail", value: 6.0 },
  { name: "Ahmed Alaaeldin", position: "FWD", country: "Qatar", clubTeam: "Al-Gharafa", value: 4.5 },
  { name: "Khalid Muneer", position: "FWD", country: "Qatar", clubTeam: "Al-Sadd", value: 4.0 },

  // ===== IRAQ =====
  { name: "Jalal Hassan", position: "GK", country: "Iraq", clubTeam: "Al-Quwa Al-Jawiya", value: 4.0 },
  { name: "Mohammed Hamid", position: "GK", country: "Iraq", clubTeam: "Dohuk SC", value: 3.5 },
  { name: "Ali Adnan", position: "DEF", country: "Iraq", clubTeam: "PAOK", value: 5.5 },
  { name: "Hussein Ali", position: "DEF", country: "Iraq", clubTeam: "Al-Quwa Al-Jawiya", value: 4.0 },
  { name: "Mustafa Nadhim", position: "DEF", country: "Iraq", clubTeam: "Naft Al-Wasat", value: 3.5 },
  { name: "Ahmed Ibrahim", position: "DEF", country: "Iraq", clubTeam: "Al-Zawra", value: 3.5 },
  { name: "Rebin Sulaka", position: "DEF", country: "Iraq", clubTeam: "Duhok", value: 3.5 },
  { name: "Saad Natiq", position: "DEF", country: "Iraq", clubTeam: "Al-Shorta", value: 3.5 },
  { name: "Amjed Attwan", position: "MID", country: "Iraq", clubTeam: "Al-Quwa Al-Jawiya", value: 4.0 },
  { name: "Alaa Abdul-Zahra", position: "MID", country: "Iraq", clubTeam: "PAFC Paok", value: 5.0 },
  { name: "Bashar Resan", position: "MID", country: "Iraq", clubTeam: "Al-Shorta", value: 4.5 },
  { name: "Yousif Amir", position: "MID", country: "Iraq", clubTeam: "Naft Al-Wasat", value: 4.0 },
  { name: "Salam Shakir", position: "MID", country: "Iraq", clubTeam: "Erbil SC", value: 4.0 },
  { name: "Osama Rashid", position: "MID", country: "Iraq", clubTeam: "Al-Quwa Al-Jawiya", value: 5.0 },
  { name: "Mohanad Ali", position: "MID", country: "Iraq", clubTeam: "Al-Minaa", value: 4.0 },
  { name: "Dhurgham Ismail", position: "MID", country: "Iraq", clubTeam: "Dohuk SC", value: 4.0 },
  { name: "Aymen Hussein", position: "FWD", country: "Iraq", clubTeam: "Al-Quwa Al-Jawiya", value: 6.5 },
  { name: "Ahmed Yasin", position: "FWD", country: "Iraq", clubTeam: "Erbil SC", value: 5.0 },
  { name: "Hamza Saheb", position: "FWD", country: "Iraq", clubTeam: "Al-Zawra", value: 4.5 },
  { name: "Mohanad Ridha", position: "FWD", country: "Iraq", clubTeam: "Al-Quwa Al-Jawiya", value: 5.5 },
  { name: "Hammam Mohammed", position: "FWD", country: "Iraq", clubTeam: "Al-Shorta", value: 4.0 },
  { name: "Zidane Iqbal", position: "MID", country: "Iraq", clubTeam: "FC Utrecht", value: 5.5 },

  // ===== PANAMA =====
  { name: "Luis Mejía", position: "GK", country: "Panama", clubTeam: "Independiente", value: 4.5 },
  { name: "Orlando Mosquera", position: "GK", country: "Panama", clubTeam: "Estudiantes", value: 3.5 },
  { name: "Eric Davis", position: "DEF", country: "Panama", clubTeam: "New England Revolution", value: 4.5 },
  { name: "Harold Cummings", position: "DEF", country: "Panama", clubTeam: "San José Earthquakes", value: 4.5 },
  { name: "Édgar Yoel Bárcenas", position: "DEF", country: "Panama", clubTeam: "Olimpia", value: 4.0 },
  { name: "Fidel Escobar", position: "DEF", country: "Panama", clubTeam: "New York City FC", value: 4.5 },
  { name: "Anibal Godoy", position: "MID", country: "Panama", clubTeam: "Nashville SC", value: 5.5 },
  { name: "Adalberto Carrasquilla", position: "MID", country: "Panama", clubTeam: "Houston Dynamo", value: 5.5 },
  { name: "Rolando Blackburn", position: "MID", country: "Panama", clubTeam: "Club Olimpia", value: 4.5 },
  { name: "César Blackman", position: "MID", country: "Panama", clubTeam: "Colo-Colo", value: 4.5 },
  { name: "Aníbal Godoy", position: "MID", country: "Panama", clubTeam: "Nashville SC", value: 5.0 },
  { name: "Armando Cooper", position: "MID", country: "Panama", clubTeam: "Club Mazatlán", value: 4.5 },
  { name: "Michael Murillo", position: "DEF", country: "Panama", clubTeam: "Anderlecht", value: 5.5 },
  { name: "José Luis Rodríguez", position: "DEF", country: "Panama", clubTeam: "Zulia FC", value: 4.0 },
  { name: "Jesús Cisneros", position: "MID", country: "Panama", clubTeam: "Estudiantes", value: 4.0 },
  { name: "Edgar Barcenas", position: "MID", country: "Panama", clubTeam: "Olimpia", value: 4.0 },
  { name: "Rolando Blackburn", position: "FWD", country: "Panama", clubTeam: "Club Olimpia", value: 5.0 },
  { name: "Ismael Díaz", position: "FWD", country: "Panama", clubTeam: "Deportivo Indie", value: 5.5 },
  { name: "Gabriel Torres", position: "FWD", country: "Panama", clubTeam: "Al-Arabi", value: 5.0 },
  { name: "Freddie Góndola", position: "FWD", country: "Panama", clubTeam: "Seattle Sounders", value: 4.5 },
  { name: "Cecilio Waterman", position: "FWD", country: "Panama", clubTeam: "Columbus Crew", value: 5.0 },
  { name: "Ronaldo Córdoba", position: "DEF", country: "Panama", clubTeam: "Atlético Nacional", value: 4.0 },

  // ===== HONDURAS =====
  { name: "Luis López", position: "GK", country: "Honduras", clubTeam: "FC Dallas", value: 4.5 },
  { name: "Harold Fonseca", position: "GK", country: "Honduras", clubTeam: "CD Marathón", value: 3.5 },
  { name: "Maynor Figueroa", position: "DEF", country: "Honduras", clubTeam: "Houston Dynamo", value: 4.0 },
  { name: "Denil Maldonado", position: "DEF", country: "Honduras", clubTeam: "Olimpia", value: 4.0 },
  { name: "Marcelo Pereira", position: "DEF", country: "Honduras", clubTeam: "FC Juárez", value: 4.0 },
  { name: "Emilio Izaguirre", position: "DEF", country: "Honduras", clubTeam: "Motagua", value: 4.0 },
  { name: "Romell Quioto", position: "MID", country: "Honduras", clubTeam: "CF Montréal", value: 5.5 },
  { name: "Alberth Elis", position: "MID", country: "Honduras", clubTeam: "Girondins de Bordeaux", value: 6.0 },
  { name: "Kervin Arriaga", position: "MID", country: "Honduras", clubTeam: "Pumas UNAM", value: 5.0 },
  { name: "José Mario Pinto", position: "MID", country: "Honduras", clubTeam: "Club Olimpia", value: 4.5 },
  { name: "Bryan Acosta", position: "MID", country: "Honduras", clubTeam: "FC Dallas", value: 5.0 },
  { name: "Edder Delgado", position: "DEF", country: "Honduras", clubTeam: "San Jose Earthquakes", value: 4.0 },
  { name: "Juan Menjívar", position: "MID", country: "Honduras", clubTeam: "Club Social y Deportivo Platense", value: 3.5 },
  { name: "Diego Rodríguez", position: "MID", country: "Honduras", clubTeam: "Olimpia", value: 4.0 },
  { name: "Jorge Álvarez", position: "DEF", country: "Honduras", clubTeam: "CONCACAF", value: 4.0 },
  { name: "Deybi Flores", position: "MID", country: "Honduras", clubTeam: "CD Marathón", value: 4.0 },
  { name: "Anthony Lozano", position: "FWD", country: "Honduras", clubTeam: "Cádiz", value: 5.5 },
  { name: "Marek Vejmelka", position: "FWD", country: "Honduras", clubTeam: "Arizona Coyotes", value: 4.0 },
  { name: "Rigoberto Rivas", position: "FWD", country: "Honduras", clubTeam: "Barnsley", value: 5.0 },
  { name: "Jonathan Rubio", position: "FWD", country: "Honduras", clubTeam: "Xolos de Tijuana", value: 4.5 },
  { name: "Héctor Castellanos", position: "FWD", country: "Honduras", clubTeam: "Chesterfield", value: 4.0 },
  { name: "Christian Techera", position: "MID", country: "Honduras", clubTeam: "Vancouver Whitecaps", value: 4.0 },

  // ===== COSTA RICA =====
  { name: "Keylor Navas", position: "GK", country: "Costa Rica", clubTeam: "PSG", value: 6.0 },
  { name: "Patrick Sequeira", position: "GK", country: "Costa Rica", clubTeam: "Lugo", value: 3.5 },
  { name: "Bryan Oviedo", position: "DEF", country: "Costa Rica", clubTeam: "Real Salt Lake", value: 4.5 },
  { name: "Francisco Calvo", position: "DEF", country: "Costa Rica", clubTeam: "Konyaspor", value: 4.5 },
  { name: "Óscar Duarte", position: "DEF", country: "Costa Rica", clubTeam: "Al-Qadsiah", value: 4.5 },
  { name: "Ronald Matarrita", position: "DEF", country: "Costa Rica", clubTeam: "Vancouver Whitecaps", value: 4.5 },
  { name: "Keysher Fuller", position: "DEF", country: "Costa Rica", clubTeam: "Herediano", value: 4.0 },
  { name: "Juan Pablo Vargas", position: "DEF", country: "Costa Rica", clubTeam: "Colorado Rapids", value: 4.5 },
  { name: "Celso Borges", position: "MID", country: "Costa Rica", clubTeam: "Herediano", value: 5.0 },
  { name: "Yeltsin Tejeda", position: "MID", country: "Costa Rica", clubTeam: "Herediano", value: 5.0 },
  { name: "Jefferson Brenes", position: "MID", country: "Costa Rica", clubTeam: "Saprissa", value: 4.0 },
  { name: "Rándall Leal", position: "MID", country: "Costa Rica", clubTeam: "Nashville SC", value: 5.0 },
  { name: "Jurguens Montenegro", position: "MID", country: "Costa Rica", clubTeam: "Saprissa", value: 4.0 },
  { name: "Álvaro Zamora", position: "MID", country: "Costa Rica", clubTeam: "Saprissa", value: 4.0 },
  { name: "Alejandro Bran", position: "MID", country: "Costa Rica", clubTeam: "Unión Española", value: 4.0 },
  { name: "Gerson Torres", position: "MID", country: "Costa Rica", clubTeam: "Herediano", value: 4.0 },
  { name: "Bryan Ruiz", position: "FWD", country: "Costa Rica", clubTeam: "Herediano", value: 5.0 },
  { name: "Joel Campbell", position: "FWD", country: "Costa Rica", clubTeam: "León", value: 6.0 },
  { name: "Alonso Martínez", position: "FWD", country: "Costa Rica", clubTeam: "Herediano", value: 5.0 },
  { name: "Johan Venegas", position: "FWD", country: "Costa Rica", clubTeam: "Herediano", value: 5.0 },
  { name: "Josimar Alcócer", position: "FWD", country: "Costa Rica", clubTeam: "Saprissa", value: 4.0 },
  { name: "Manfred Ugalde", position: "FWD", country: "Costa Rica", clubTeam: "Spartak Moscow", value: 5.5 },

  // ===== NEW ZEALAND =====
  { name: "Oliver Sail", position: "GK", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.0 },
  { name: "Stefan Marinovic", position: "GK", country: "New Zealand", clubTeam: "Vancouver Whitecaps", value: 3.5 },
  { name: "Tommy Smith", position: "DEF", country: "New Zealand", clubTeam: "Ipswich Town", value: 5.0 },
  { name: "Michael Boxall", position: "DEF", country: "New Zealand", clubTeam: "Minnesota United", value: 4.5 },
  { name: "Liberato Cacace", position: "DEF", country: "New Zealand", clubTeam: "Empoli", value: 5.0 },
  { name: "Tim Payne", position: "DEF", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.0 },
  { name: "Nando Pijnaker", position: "DEF", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.0 },
  { name: "Dane Ingham", position: "DEF", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.0 },
  { name: "Joe Bell", position: "MID", country: "New Zealand", clubTeam: "Atlanta United", value: 5.0 },
  { name: "Marco Rojas", position: "MID", country: "New Zealand", clubTeam: "Melbourne City", value: 5.0 },
  { name: "Sarpreet Singh", position: "MID", country: "New Zealand", clubTeam: "Bayern Munich II", value: 5.0 },
  { name: "Elijah Just", position: "MID", country: "New Zealand", clubTeam: "Aarhus GF", value: 4.5 },
  { name: "Clayton Lewis", position: "MID", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.5 },
  { name: "Alex Greive", position: "MID", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.5 },
  { name: "Ben Waine", position: "FWD", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 5.0 },
  { name: "Callan Elliot", position: "FWD", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 5.0 },
  { name: "Chris Wood", position: "FWD", country: "New Zealand", clubTeam: "Nottm Forest", value: 7.5 },
  { name: "Matthew Garbett", position: "MID", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.0 },
  { name: "Logan Rogerson", position: "FWD", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 4.5 },
  { name: "Kosta Barbarouses", position: "FWD", country: "New Zealand", clubTeam: "Seattle Sounders", value: 5.0 },
  { name: "Ryan De Vries", position: "DEF", country: "New Zealand", clubTeam: "Wellington Phoenix", value: 3.5 },
  { name: "Marko Stamenic", position: "MID", country: "New Zealand", clubTeam: "FC Copenhagen", value: 5.5 },

  // ===== VENEZUELA =====
  { name: "Wuilker Faríñez", position: "GK", country: "Venezuela", clubTeam: "CF Montréal", value: 5.0 },
  { name: "Rafael Romo", position: "GK", country: "Venezuela", clubTeam: "Santos Laguna", value: 3.5 },
  { name: "Ronald Hernández", position: "DEF", country: "Venezuela", clubTeam: "AIK", value: 4.5 },
  { name: "Alexander González", position: "DEF", country: "Venezuela", clubTeam: "Al-Adalah", value: 5.0 },
  { name: "Mikel Villanueva", position: "DEF", country: "Venezuela", clubTeam: "Deportivo Táchira", value: 4.0 },
  { name: "Nahuel Ferraresi", position: "DEF", country: "Venezuela", clubTeam: "Basaksehir", value: 5.0 },
  { name: "Yordan Osorio", position: "DEF", country: "Venezuela", clubTeam: "Real Valladolid", value: 4.5 },
  { name: "Luis Mago", position: "DEF", country: "Venezuela", clubTeam: "CD Leganés", value: 4.5 },
  { name: "Tomás Rincón", position: "MID", country: "Venezuela", clubTeam: "Deportivo Táchira", value: 5.0 },
  { name: "Junior Moreno", position: "MID", country: "Venezuela", clubTeam: "DC United", value: 5.0 },
  { name: "Yangel Herrera", position: "MID", country: "Venezuela", clubTeam: "Girona", value: 7.0 },
  { name: "José Martínez", position: "MID", country: "Venezuela", clubTeam: "Philadelphia Union", value: 5.5 },
  { name: "Rómulo Otero", position: "MID", country: "Venezuela", clubTeam: "Atlético Nacional", value: 5.5 },
  { name: "Samuel Sosa", position: "MID", country: "Venezuela", clubTeam: "Cruz Azul", value: 5.0 },
  { name: "Yonathan Del Valle", position: "MID", country: "Venezuela", clubTeam: "Deportivo Táchira", value: 4.0 },
  { name: "Jefferson Savarino", position: "MID", country: "Venezuela", clubTeam: "Real Salt Lake", value: 5.5 },
  { name: "Salomón Rondón", position: "FWD", country: "Venezuela", clubTeam: "Al-Kerma", value: 6.0 },
  { name: "Josef Martínez", position: "FWD", country: "Venezuela", clubTeam: "Inter Miami", value: 6.5 },
  { name: "Darwin Machís", position: "FWD", country: "Venezuela", clubTeam: "Granada", value: 6.0 },
  { name: "Jhonder Cádiz", position: "FWD", country: "Venezuela", clubTeam: "FC Lausanne-Sport", value: 5.0 },
  { name: "Eduard Bello", position: "FWD", country: "Venezuela", clubTeam: "Atlético Tucumán", value: 5.0 },
  { name: "Eric Ramirez", position: "FWD", country: "Venezuela", clubTeam: "Salernitana", value: 5.5 },

  // ===== WALES =====
  { name: "Wayne Hennessey", position: "GK", country: "Wales", clubTeam: "Nottm Forest", value: 4.5 },
  { name: "Danny Ward", position: "GK", country: "Wales", clubTeam: "Leicester", value: 4.0 },
  { name: "Ben Davies", position: "DEF", country: "Wales", clubTeam: "Tottenham", value: 5.5 },
  { name: "Chris Mepham", position: "DEF", country: "Wales", clubTeam: "Bournemouth", value: 5.0 },
  { name: "Neco Williams", position: "DEF", country: "Wales", clubTeam: "Nottm Forest", value: 5.5 },
  { name: "Connor Roberts", position: "DEF", country: "Wales", clubTeam: "Burnley", value: 5.0 },
  { name: "Ben Cabango", position: "DEF", country: "Wales", clubTeam: "Swansea City", value: 4.5 },
  { name: "Tom Lockyer", position: "DEF", country: "Wales", clubTeam: "Luton Town", value: 4.5 },
  { name: "Aaron Ramsey", position: "MID", country: "Wales", clubTeam: "Nice", value: 6.5 },
  { name: "Joe Allen", position: "MID", country: "Wales", clubTeam: "Swansea City", value: 5.0 },
  { name: "Ethan Ampadu", position: "MID", country: "Wales", clubTeam: "Leeds", value: 5.5 },
  { name: "Harry Wilson", position: "MID", country: "Wales", clubTeam: "Fulham", value: 6.0 },
  { name: "Joe Morrell", position: "MID", country: "Wales", clubTeam: "Portsmouth", value: 4.5 },
  { name: "Dylan Levitt", position: "MID", country: "Wales", clubTeam: "Dundee Utd", value: 4.5 },
  { name: "Matthew Smith", position: "MID", country: "Wales", clubTeam: "Milton Keynes Dons", value: 4.0 },
  { name: "Jordan James", position: "MID", country: "Wales", clubTeam: "Birmingham City", value: 5.0 },
  { name: "Gareth Bale", position: "FWD", country: "Wales", clubTeam: "LAFC", value: 7.5 },
  { name: "Daniel James", position: "FWD", country: "Wales", clubTeam: "Leeds", value: 6.5 },
  { name: "Kieffer Moore", position: "FWD", country: "Wales", clubTeam: "Ipswich", value: 5.5 },
  { name: "Mark Harris", position: "FWD", country: "Wales", clubTeam: "Cardiff City", value: 4.5 },
  { name: "Brennan Johnson", position: "FWD", country: "Wales", clubTeam: "Nottm Forest", value: 6.5 },
  { name: "Tyler Roberts", position: "FWD", country: "Wales", clubTeam: "Queens Park Rangers", value: 4.5 },

  // ===== PARAGUAY =====
  { name: "Antony Silva", position: "GK", country: "Paraguay", clubTeam: "Querétaro", value: 4.5 },
  { name: "Alfredo Aguilar", position: "GK", country: "Paraguay", clubTeam: "Olimpia", value: 3.5 },
  { name: "Iván Piris", position: "DEF", country: "Paraguay", clubTeam: "Club Libertad", value: 4.0 },
  { name: "Robert Rojas", position: "DEF", country: "Paraguay", clubTeam: "River Plate", value: 5.5 },
  { name: "Fabián Balbuena", position: "DEF", country: "Paraguay", clubTeam: "Club Cerro Porteño", value: 5.0 },
  { name: "Junior Alonso", position: "DEF", country: "Paraguay", clubTeam: "Atlético Mineiro", value: 5.5 },
  { name: "Santiago Arzamendia", position: "DEF", country: "Paraguay", clubTeam: "Cadiz", value: 5.0 },
  { name: "Jorge Morel", position: "DEF", country: "Paraguay", clubTeam: "Guaraní", value: 4.0 },
  { name: "Mathías Villasanti", position: "MID", country: "Paraguay", clubTeam: "Grêmio", value: 5.5 },
  { name: "Ángel Cardozo Lucena", position: "MID", country: "Paraguay", clubTeam: "Libertad", value: 4.5 },
  { name: "Andrés Cubas", position: "MID", country: "Paraguay", clubTeam: "RC Lens", value: 5.5 },
  { name: "Alejandro Romero Gamarra", position: "MID", country: "Paraguay", clubTeam: "Club Olimpia", value: 4.5 },
  { name: "Braian Ojeda", position: "MID", country: "Paraguay", clubTeam: "Nottm Forest", value: 5.0 },
  { name: "Gastón Giménez", position: "MID", country: "Paraguay", clubTeam: "Columbus Crew", value: 5.0 },
  { name: "Miguel Almirón", position: "MID", country: "Paraguay", clubTeam: "Newcastle", value: 7.0 },
  { name: "Óscar Romero", position: "MID", country: "Paraguay", clubTeam: "Club Olimpia", value: 5.5 },
  { name: "Antonio Sanabria", position: "FWD", country: "Paraguay", clubTeam: "Torino", value: 6.0 },
  { name: "Adam Bareiro", position: "FWD", country: "Paraguay", clubTeam: "San Lorenzo", value: 5.5 },
  { name: "Gabriel Avalos", position: "FWD", country: "Paraguay", clubTeam: "Club Libertad", value: 4.5 },
  { name: "Derlis González", position: "FWD", country: "Paraguay", clubTeam: "Olimpia", value: 5.0 },
  { name: "Alex Arce", position: "FWD", country: "Paraguay", clubTeam: "Club Olimpia", value: 4.5 },
  { name: "Ángel Romero", position: "FWD", country: "Paraguay", clubTeam: "San Lorenzo", value: 5.5 },

  // ===== UZBEKISTAN =====
  { name: "Eldor Shomurodov", position: "FWD", country: "Uzbekistan", clubTeam: "Roma", value: 6.5 },
  { name: "Otabek Shukurov", position: "GK", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.0 },
  { name: "Sarvarbek Toshev", position: "GK", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 3.5 },
  { name: "Dostonbek Khamdamov", position: "DEF", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.0 },
  { name: "Sanjar Tursunov", position: "DEF", country: "Uzbekistan", clubTeam: "Lokomotiv Tashkent", value: 4.0 },
  { name: "Dzhaloliddin Masharipov", position: "MID", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 5.5 },
  { name: "Bobur Abdixoliqov", position: "MID", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 5.0 },
  { name: "Nodir Tursunov", position: "MID", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.5 },
  { name: "Abbosbek Fayzullayev", position: "MID", country: "Uzbekistan", clubTeam: "Red Star Belgrade", value: 5.5 },
  { name: "Ruslan Nishonov", position: "DEF", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.0 },
  { name: "Shamsiddin Shomurodov", position: "DEF", country: "Uzbekistan", clubTeam: "Nasaf", value: 4.0 },
  { name: "Jaloliddin Masharipov", position: "MID", country: "Uzbekistan", clubTeam: "Al-Qadsiah", value: 5.0 },
  { name: "Otabek Fayzullayev", position: "MID", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.5 },
  { name: "Akramjon Komilov", position: "MID", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.0 },
  { name: "Khurshid Makhkamov", position: "FWD", country: "Uzbekistan", clubTeam: "FK Navbahor", value: 4.5 },
  { name: "Shukhrat Mukhammad", position: "DEF", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.0 },
  { name: "Ildar Abdullayev", position: "FWD", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 5.0 },
  { name: "Jasur Yaxshiboyev", position: "FWD", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 5.0 },
  { name: "Husayn Norqoʻziyev", position: "FWD", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.5 },
  { name: "Behruz Ochilov", position: "MID", country: "Uzbekistan", clubTeam: "Metallurg", value: 4.0 },
  { name: "Hojiakbar Alijonov", position: "DEF", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 3.5 },
  { name: "Manuchekhr Ergashev", position: "FWD", country: "Uzbekistan", clubTeam: "Pakhtakor", value: 4.5 },

  // ===== JORDAN =====
  { name: "Amer Shafi", position: "GK", country: "Jordan", clubTeam: "Al-Aqaba", value: 4.0 },
  { name: "Yahia Al-Shagran", position: "GK", country: "Jordan", clubTeam: "Al-Faisaly", value: 3.5 },
  { name: "Yazan Al-Naimat", position: "DEF", country: "Jordan", clubTeam: "Al-Faisaly", value: 4.0 },
  { name: "Baha Faisal", position: "DEF", country: "Jordan", clubTeam: "Al-Wehdat", value: 4.0 },
  { name: "Omar Al-Dameeh", position: "DEF", country: "Jordan", clubTeam: "Al-Ramtha", value: 3.5 },
  { name: "Abdallah Nasib", position: "DEF", country: "Jordan", clubTeam: "Al-Faisaly", value: 3.5 },
  { name: "Noor Al-Rawabdeh", position: "DEF", country: "Jordan", clubTeam: "Al-Wehdat", value: 3.5 },
  { name: "Hesham Abu Ali", position: "DEF", country: "Jordan", clubTeam: "FC Lausanne-Sport", value: 4.5 },
  { name: "Ahmad Gharib", position: "MID", country: "Jordan", clubTeam: "Hapoel Tel Aviv", value: 5.0 },
  { name: "Musa Al-Tamari", position: "MID", country: "Jordan", clubTeam: "Montpellier", value: 5.5 },
  { name: "Ahmad Ibrahim", position: "MID", country: "Jordan", clubTeam: "Al-Faisaly", value: 4.0 },
  { name: "Fahad Al-Naimat", position: "MID", country: "Jordan", clubTeam: "Al-Faisaly", value: 4.0 },
  { name: "Mohammad Abu Zreiq", position: "MID", country: "Jordan", clubTeam: "Al-Qadsiah", value: 5.0 },
  { name: "Saif Almujahid", position: "MID", country: "Jordan", clubTeam: "Al-Faisaly", value: 4.0 },
  { name: "Ahmad Al-Qudah", position: "MID", country: "Jordan", clubTeam: "Al-Ramtha", value: 4.0 },
  { name: "Raed Albatayha", position: "MID", country: "Jordan", clubTeam: "Vitesse", value: 4.5 },
  { name: "Ayoub Asyrie", position: "FWD", country: "Jordan", clubTeam: "Heracles", value: 5.0 },
  { name: "Eslam Ahmad", position: "FWD", country: "Jordan", clubTeam: "Al-Faisaly", value: 4.5 },
  { name: "Yazan Al-Arab", position: "FWD", country: "Jordan", clubTeam: "Al-Qadsiah", value: 5.5 },
  { name: "Moussa Al-Tamari", position: "FWD", country: "Jordan", clubTeam: "Angers", value: 5.0 },
  { name: "Ahmad Sarrar", position: "FWD", country: "Jordan", clubTeam: "Al-Faisaly", value: 4.0 },
  { name: "Mutasem Dhaher", position: "FWD", country: "Jordan", clubTeam: "Al-Ramtha", value: 3.5 },
];

// Merge and deduplicate
const allPlayers = [...players, ...extraPlayers];

async function main() {
  console.log("Seeding database...");

  await prisma.gameweekPlayerStat.deleteMany();
  await prisma.gameweekPoints.deleteMany();
  await prisma.transfer.deleteMany();
  await prisma.userPlayer.deleteMany();
  await prisma.userTeam.deleteMany();
  await prisma.userChip.deleteMany();
  await prisma.leagueMember.deleteMany();
  await prisma.league.deleteMany();
  await prisma.user.deleteMany();
  await prisma.gameWeek.deleteMany();
  await prisma.player.deleteMany();

  for (const p of allPlayers) {
    await prisma.player.create({ data: p });
  }
  console.log(`Created ${allPlayers.length} players`);

  for (const gw of gameweeks) {
    await prisma.gameWeek.create({ data: { ...gw, isActive: gw.number === 1 } });
  }
  console.log(`Created ${gameweeks.length} gameweeks`);

  console.log("Done!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
